### ISSUE TITLE
Centos7 安装出错。。。。

### ISSUE THREAD

**Issue by qwqcode** [maicong/LNMP#13]
[Notice] Config service ... 
mv: 无法获取"/etc/nginx/conf.d/*" 的文件状态(stat): 没有那个文件或目录
chown: 无效的用户: "mysql:mysql"
[Notice] Start service ... 
Failed to execute operation: No such file or directory
Created symlink from /etc/systemd/system/multi-user.target.wants/php-fpm.service to /usr/lib/systemd/system/php-fpm.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/nginx.service to /usr/lib/systemd/system/nginx.service.
success
success
success
Failed to start mysqld.service: Unit mysqld.service failed to load: No such file or directory.
lnmp.sh:行407: mysqladmin: 未找到命令
lnmp.sh:行408: mysqladmin: 未找到命令
lnmp.sh:行409: mysql: 未找到命令
 [LNMP] Sorry, Install Failed.

**Comment by maicong** [comment]
= =.
