### ISSUE TITLE
连接Mysql出现No such file or directory

### ISSUE THREAD

**Issue by MoeGrid** [maicong/LNMP#14]
如题

**Comment by maicong** [comment]
= — =，你选择的是哪款 MySQL

**Comment by MoeGrid** [comment]
mysql  Ver 14.14 Distrib 5.6.30, for Linux (x86_64) using  EditLine wrapper
问题已经解决
原因是my.ini中设置的sock文件位置是/home/userdata/mysqld.sock
php.ini中设置的是/var/lib/mysql/mysql.sock

**Comment by maicong** [comment]
为了方便备份和维护，我把数据库和网站数据都搬到了 `/home` 下面，问题解决了就好。
