### ISSUE TITLE
请问从哪个文件内可以找到 php配置  open_basedir

### ISSUE THREAD

**Issue by CrazyCodes** [maicong/LNMP#15]

**Comment by CrazyCodes** [comment]
大神，看到请回复。。我用laravel搭建的程序报错

Warning: file_exists(): open_basedir restriction in effect. File(/home/wwwroot/weixin/bootstrap/cache/compiled.php) is not within the allowed path(s): (/home/wwwroot/weixin/public:/usr/share/pear:/usr/share/php:/etc/phpMyAdmin:/tmp:/proc) in /home/wwwroot/weixin/bootstrap/autoload.php on line 32 int(11)

**Comment by maicong** [comment]
[/etc/nginx/fastcgi_params#L25](https://github.com/maicong/LNMP/blob/master/etc/nginx/fastcgi_params#L25)

**Comment by CrazyCodes** [comment]
多谢了
