### ISSUE TITLE
很遗憾，安装功败垂成

### ISSUE THREAD

**Issue by ukhack** [maicong/LNMP#19]
在安装的末尾:
Error: Package: php-mcrypt-5.5.38-7.el7.remi.x86_64 (remi-php55)
           Requires: libmcrypt.so.4()(64bit)
Error: Package: php-mssql-5.5.38-7.el7.remi.x86_64 (remi-php55)
           Requires: libsybdb.so.5()(64bit)
Error: Package: php-mssql-5.5.38-7.el7.remi.x86_64 (remi-php55)
           Requires: libct.so.4()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[Notice] Config service ...
mv: cannot stat '/etc/php-fpm.d/*': No such file or directory
mv: cannot stat '/etc/php.ini': No such file or directory
mv: cannot stat '/etc/nginx/conf.d/*': No such file or directory
mv: cannot stat '/etc/nginx/nginx.conf': No such file or directory
mv: cannot stat '/etc/nginx/fastcgi_params': No such file or directory
[Notice] Start service ...
Created symlink from /etc/systemd/system/mysql.service to /usr/lib/systemd/system/mysqld.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/mysqld.service to /usr/lib/systemd/system/mysqld.service.
Failed to execute operation: No such file or directory
Failed to execute operation: No such file or directory
Job for firewalld.service failed because the control process exited with error code. See "systemctl status firewalld.service" and "journalctl -xe" for details.
Traceback (most recent call last):
  File "/usr/bin/firewall-cmd", line 24, in <module>
    from gi.repository import GObject
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 37, in <module>
    from . import _gi
ImportError: /usr/lib64/python2.7/site-packages/gi/_gi.so: undefined symbol: g_type_check_instance_is_fundamentally_a
Traceback (most recent call last):
  File "/usr/bin/firewall-cmd", line 24, in <module>
    from gi.repository import GObject
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 37, in <module>
    from . import _gi
ImportError: /usr/lib64/python2.7/site-packages/gi/_gi.so: undefined symbol: g_type_check_instance_is_fundamentally_a
Traceback (most recent call last):
  File "/usr/bin/firewall-cmd", line 24, in <module>
    from gi.repository import GObject
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 37, in <module>
    from . import _gi
ImportError: /usr/lib64/python2.7/site-packages/gi/_gi.so: undefined symbol: g_type_check_instance_is_fundamentally_a
Failed to start php-fpm.service: Unit not found.
Failed to start nginx.service: Unit not found.
mysqladmin: connect to server at 'restorevps.com' failed
error: 'Access denied for user 'root'@'restorevps.com' (using password: YES)'
 [LNMP] Sorry, Install Failed.
服务器在洛杉矶

**Comment by ukhack** [comment]
排查后发现系统本身不存在libmcrypt.so.4()(64bit)但是必须这个依赖
一番摸索以后找到了这个文件，手动输入以下命令：
https://centos.pkgs.org/7/epel-x86_64/libmcrypt-2.5.8-13.el7.x86_64.rpm.html
wget http://dl.fedoraproject.org/pub/epel/7/x86_64/l/libmcrypt-2.5.8-13.el7.x86_64.rpm
yum install libmcrypt-2.5.8-13.el7.x86_64.rpm能修复这个问题。
希望作者能加入到安装脚本中去。

**Comment by maicong** [comment]
好的，感谢提供问题~

**Comment by maicong** [comment]
可以试试开发版： https://github.com/maicong/LNMP/tree/dev
