### ISSUE TITLE
aliyun centos 7.2 mysql5.6安装失败

### ISSUE THREAD

**Issue by jstony** [maicong/LNMP#20]
安装脚本跑到最后出现如下错误，
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'izbpxxxxxx' failed
error: 'Access denied for user 'root'@'izbpxxxxxx' (using password: YES)'
Warning: Using a password on the command line interface can be insecure.

mysql 5.6安装失败

**Comment by maicong** [comment]
试试 dev 分支？

```bash
## 确保 wget 命令已经安装，已安装请忽略此步
yum install wget -y

## 执行安装脚本
sh -c "$(wget https://cdn.rawgit.com/maicong/LNMP/dev/lnmp.sh -O -)"

# 如果想保存安装日志，请将 log 输出到指定文件
# sh -c "$(wget https://cdn.rawgit.com/maicong/LNMP/dev/lnmp.sh -O -)" 2>&1 | tee lnmp.log
```

**Comment by xiaofami** [comment]
centos7 同样遇到mysql问题，提示mysqli_real_connect(): (HY000/2002): No such file or directory
mysql.sock也不存在
