### ISSUE TITLE
登陆phpMyAdmin报错，错误 mysqli::real_connect(): (HY000/2002): No such file or directory

### ISSUE THREAD

**Issue by syh0304** [maicong/LNMP#22]
发现phpMyAdmin文件夹下缺少配置文件，自己创建了配置文件，
的配置文件config.sample.inc.php改成config.inc.php，并更改为$cfg['Servers'][$i]['host'] = '127.0.0.1';
结果还是报错

**Comment by maicong** [comment]
汗颜，我并没有对 phpMyAdmin 做过多测试，因为很少使用到。

**Comment by maicong** [comment]
你可以使用客户端软件连接数据库
