### ISSUE TITLE
如果有像lnmp.org那样专门的网站来推广这个轻量级的LEMP就好了

### ISSUE THREAD

**Issue by baoang** [maicong/LNMP#23]
Vultr上有专门的LEMP，国内有lnmp.org这样的专门的网站发布LEMP STACK，看了下喵主的这款，更加精简，如果在博客以外还能有精力来架设一个LNMP的网站专门介绍和发布自己的这款STACK就更好了。

**Comment by maicong** [comment]
目前这只是个人使用的项目，没有更多精力去维护一个官网。
