### ISSUE TITLE
Start up bug

### ISSUE THREAD

**Issue by mrl22** [maicong/LNMP#24]
Great set of scripts.

I have installed on Centos 7 and when I reboot I get "502 Bad Gateway" when visiting PHP pages.

I think this is the error: 
`[12-Apr-2018 16:11:26] ERROR: Unable to create the PID file (/run/php-fpm/php-fpm-index.pid).: No such file or directory (2)`

To get around this I have added the following to /etc/rc.local

`mkdir /run/php-fpm`
`service vhost stop`
`service vhost start`

**Comment by mrl22** [comment]
If I do not run `service vhost stop` then I get the following error: `[ERROR] index host maybe running or not exist`

**Comment by maicong** [comment]
OK, I will check it right now.

**Comment by mrl22** [comment]
I am happy to give you access to a virtual machine for you to play around with that has this issue if you like.

**Comment by maicong** [comment]
I'm sorry to have kept you waiting for a long time. I think i fixed it, please try again.
