### ISSUE TITLE
 [LNMP] Sorry, Install Failed. 

### ISSUE THREAD

**Issue by Chastex** [maicong/LNMP#4]
[Notice] Start service ... 
lnmp.sh: line 392: systemctl: command not found
lnmp.sh: line 393: systemctl: command not found
lnmp.sh: line 394: systemctl: command not found
lnmp.sh: line 395: systemctl: command not found
lnmp.sh: line 397: systemctl: command not found
lnmp.sh: line 399: firewall-cmd: command not found
lnmp.sh: line 400: firewall-cmd: command not found
lnmp.sh: line 401: firewall-cmd: command not found
lnmp.sh: line 403: systemctl: command not found
lnmp.sh: line 404: systemctl: command not found
lnmp.sh: line 405: systemctl: command not found
lnmp.sh: line 407: mysqladmin: command not found
lnmp.sh: line 408: mysqladmin: command not found
lnmp.sh: line 409: mysql: command not found

**Comment by maicong** [comment]
This shell script just run on CentOS 7.

**Comment by Chastex** [comment]
sorry,i got it.

**Comment by maicong** [comment]
:)

**Comment by Chastex** [comment]
CentOS 7.

```
Failed to start mysqld.service: Unit mysqld.service failed to load: No such file or directory.
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/home/userdata/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/home/userdata/mysqld.sock' exists!
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/home/userdata/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/home/userdata/mysqld.sock' exists!
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/home/userdata/mysqld.sock' (2)

```

im new so dont know what to search... please

**Comment by maicong** [comment]
Please show me the full log. If you can't find it, try this:
- 1. run `bash lnmp.sh` and select `Uninstall`
- 2. run `bash lnmp.sh 2>&1 | tee lnmp.log` and select `Install`
- 3. wait for the installation to complete and show me the `lnmp.log`

**Comment by maicong** [comment]
Are you ok?

**Comment by Chastex** [comment]
Thanks！it works
