### ISSUE TITLE
一键脚本安装PHPMYADMIN登录错误

### ISSUE THREAD

**Issue by Stoneplug** [maicong/LNMP#6]
麦葱， 你好， 按你的一键脚本安装完成，PHPMYADMIN页面能正常访问，但输入ROOT及密码后，提示#2002 - No such file or directory — The server is not responding (or the local server's socket is not correctly configured).，求解决方法。谢谢

**Comment by maicong** [comment]
您看下 mysql  启动没有：`service mysql status`，再检查下 `/home/userdata/mysqld.sock` 是否存在。

**Comment by Stoneplug** [comment]
谢谢你的回复，mysql启动正常，你说的目录也存在，我在PHPMYADMIN登录页面用localhost不能登录，换成127.0.0.1后才能正常登录。 这样是我哪里配置有问题么？

**Comment by maicong** [comment]
这个问题我也遇到过，目前还不知道是哪里导致的，有解决方案了我会尽快修复。
