### ISSUE TITLE
加些常用的扩展就更棒了

### ISSUE THREAD

**Issue by weijer** [maicong/LNMP#8]
例如redis  imagick swoole等

**Comment by maicong** [comment]
Redis 安装方法请参考: https://www.digitalocean.com/community/tutorials/how-to-configure-a-redis-cluster-on-centos-7
本脚本用的是 Remi 的 PHP 源，请 cmd(ctrl) + f 搜索 imagick：
http://rpms.remirepo.net/enterprise/7/remi/x86_64/repoview/development.libraries.group.html
ImageMagick ：http://rpms.remirepo.net/enterprise/7/remi/x86_64/repoview/ImageMagick-last-libs.html
swoole 暂时没有找到 rpm，不过你可以手动编译安装：https://github.com/swoole/swoole-src
