### ISSUE TITLE
添加vhost之后，出现502错误

### ISSUE THREAD

**Issue by jinyu121** [maicong/LNMP#9]
默认是一个vhost。现在用`service vhost add`再添加一个vhost，比如叫做foo。那么一旦启用foo，重启服务器，所有站点都会502.看log发现是php-fpm的管道没有建立。但是php-fpm不报错。`service php-fpm restart`无效。

故障排查，逐个删除vhost，删除index或者foo，只留下一个vhost，`service php-fpm restart` ,可以正常生成管道文件，网站可以访问。

so，配置文件哪里有冲突么？我是Nginx新手看不出来……

环境：Cent OS 7， OVZ的Minimum模板。

**Comment by maicong** [comment]
目前使用 `php-fpm` 重启站点存在部分问题，你可以使用 `service vhost stop foo; service vhost start foo;` 方式重启。
